// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJ5T1sxm-C7bvCUzZyFh7UhMDCXZ6rq0',
    appId: '1:100838094614:web:433ce103e3ceb977c98237',
    messagingSenderId: '100838094614',
    projectId: 'chatplus-315cc',
    authDomain: 'chatplus-315cc.firebaseapp.com',
    storageBucket: 'chatplus-315cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxD6U_U1khke_BE_Quxhh7J8ekPhcrNw',
    appId: '1:100838094614:android:ec88cb6a9c979088c98237',
    messagingSenderId: '100838094614',
    projectId: 'chatplus-315cc',
    storageBucket: 'chatplus-315cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLnLugHw8mwpvtTwptvBz69ntEco6-fM',
    appId: '1:100838094614:ios:4a62ecf80c470983c98237',
    messagingSenderId: '100838094614',
    projectId: 'chatplus-315cc',
    storageBucket: 'chatplus-315cc.appspot.com',
    iosBundleId: 'com.example.chatWe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLnLugHw8mwpvtTwptvBz69ntEco6-fM',
    appId: '1:100838094614:ios:e896ba4963283e6bc98237',
    messagingSenderId: '100838094614',
    projectId: 'chatplus-315cc',
    storageBucket: 'chatplus-315cc.appspot.com',
    iosBundleId: 'com.example.chatWe.RunnerTests',
  );
}
